.\"	$OpenBSD$
.\"
.\" Copyright (c) 2014 Alexandre Ratchov <alex@caoua.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt XVOLKEYS 1
.Os
.Sh NAME
.Nm sndiokeys
.Nd
control sndiod with hot-keys
.Sh SYNOPSIS
.Nm sndiokeys
.Op Fl D
.Op Fl v
.Op Fl f Ar device
.Sh DESCRIPTION
.Nm
registers hot-keys in
.Xr X 7
to control
.Xr sndiod 8 .
Pressing the following keys while the
Control and Alt keys are held down
change
.Xr sndiod 8
controls as follows:
.Pp
.Bl -tag -width "XXXX" -offset indent -compact
.It +
increase audio output level
.It -
decrease audio output level
.It 0
cycle through audio devices.
.El
.Pp
.Nm
is meant to be started as background process by
.Xr xinit 1
or
.Xr xdm 1
session startup scripts.
It exits when X session terminates.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl b
Emmit audible beep when audio device is changed.
.It Fl D
Daemonize.
.It Fl f Ar device
Audio device to control.
.It Fl v
Increase log verbosity.
.El
.Sh SEE ALSO
.Xr sndioctl 1
.Xr startx 1
.Xr sndio 7
.Xr X 7
.Xr sndiod 8
