.\"	$OpenBSD$
.\"
.\" Copyright (c) 2014-2021 Alexandre Ratchov <alex@caoua.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt SNDIOKEYS 1
.Os
.Sh NAME
.Nm sndiokeys
.Nd
control sndiod with hot-keys and play keyboard bells
.Sh SYNOPSIS
.Nm sndiokeys
.Op Fl a
.Op Fl b Ar [mod+...]key:func
.Op Fl D
.Op Fl s
.Op Fl v
.Op Fl f Ar device
.Sh DESCRIPTION
.Nm
registers hot-keys in
.Xr X 7
to control
.Xr sndiod 8 .
It can also replace the
.Xr X 7
keyboard bells by audible beeps on the audio device.
.Pp
The default key-bindings are as follows:
.Pp
.Bl -tag -width "Control+Mod1+minus" -offset indent -compact
.It Control+Mod1+plus
increase output level
.It Control+Mod1+minus
decrease output level
.It Control+Mod1+0
cycle through audio devices.
.El
.Pp
.Nm
is meant to be started as background process by
.Xr startx 1
or the display manager session startup scripts.
It exits when X session terminates.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl a
Play audible beeps on the audio device in place of the
.Xr X 7
keyboard bells.
.It Fl b Ar [modifier+...]key:function
Perform
.Cm function
whenever
.Cm key
is pressed while
.Cm modifier
keys are held down.
Key names correspond to symbols defined in
.Pa /usr/X11R6/include/X11/keysymdef.h
with the
.Cm XK_
prefix removed.
Supported modifiers are: Control, Mod1, and Mod4.
On most setups, Mod1 and Mod4 correspond to the Alt and Windows keys.
Function names are:
.Pp
.Bl -tag -width "cycle_dev" -offset indent -compact
.It inc_level
increase output level
.It dec_level
decrease output level
.It cycle_dev
cycle through audio devices
.El
.It Fl D
Daemonize.
.It Fl f Ar device
Audio device to control.
.It Fl s
Don't emit audible beep when output level or audio device are changed.
.It Fl v
Increase log verbosity.
.El
.Sh EXAMPLES
Increase or decrease output level when Up or Down keys are pressed
while the Control and Mod1 keys are held down:
.Bd -literal -offset indent
$ sndiokeys -b Control+Mod1+Up:inc_level \\
            -b Control+Mod1+Down:dec_level
.Ed
.Pp
Make volume keys found on multimedia keyboards control the output level:
.Bd -literal -offset indent
$ sndiokeys -b XF86_AudioRaiseVolume:inc_level \\
            -b XF86_AudioLowerVolume:dec_level
.Ed
.Sh SEE ALSO
.Xr sndioctl 1 ,
.Xr startx 1 ,
.Xr sndio 7 ,
.Xr X 7 ,
.Xr sndiod 8
.Sh BUGS
Volume keys of multimedia keyboards may already control output level
using another mechanism.
If so, using the same keys in
.Nm
may cause unpredictable output level changes.
